excerpt_separator:  <!--snip-->

collections:
 articles:
  output: true
 pages:
  output: true

defaults:
 -
  scope:
   path: ""
   type: "pages"
  values:
   layout: "minimal"
 -
  scope:
   path: ""
   type: "articles"
  values:
   layout: "article"

exclude:
 - CNAME
 - config.json
